# Generated by Django 4.2.3 on 2024-05-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typecamp_app', '0005_profile_total_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wpm',
            field=models.IntegerField(default=0),
        ),
    ]
