# Generated by Django 4.2.3 on 2024-05-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typecamp_app', '0006_profile_wpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mistakes', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
                ('total_keys', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='quote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
