# Generated by Django 4.2.3 on 2024-05-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typecamp_app', '0009_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
