# Generated by Django 4.2.3 on 2024-05-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typecamp_app', '0011_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('-test_date',)},
        ),
        migrations.AddField(
            model_name='history',
            name='test_num',
            field=models.IntegerField(default=1),
        ),
    ]
