# Generated by Django 5.0.6 on 2024-06-02 05:10

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typecamp_app', '0014_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='game_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['id']),
        ),
    ]
